---
title: Enigma
name: enigma
upperName: ENIGMA
markdown: kramdown
baseurl: "/enigma"
defaults:
- scope:
    path: docs
    type: pages
  values:
    layout: docs
    sectionid: docs
- scope:
    path: inv
    type: pages
  values:
    layout: inv
    sectionid: inv
- scope:
    path: about
    type: pages
  values:
    layout: about
    sectionid: about
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: :compressed
